
services:
  pgdb:
    image: postgres:14
    container_name: nextbi-pgdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: IncubationSystem
    volumes:
      - ./nextbi_postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: nextbi-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - pgdb

  nextbi-server:
    image: nextbi-server:1.0
    container_name: nextbi-server
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - pgdb

  nextbi-webapp:
    image: nextbi:1.0
    container_name: nextbi-webapp
    ports:
      - "8081:3000"
    restart: always
    depends_on:
      - nextbi-server
